# Generated by Django 4.0.3 on 2022-03-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_module', '0002_remove_legoset_maintag_remove_legoset_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legoset',
            name='RatingValue',
        ),
        migrations.RemoveField(
            model_name='legoset',
            name='RatingVotes',
        ),
    ]
